### ISSUE TITLE
Question , Great idea 

### ISSUE THREAD

**Issue by fagurto** [rycus86/podlike#3]
is there any intention of this to become a thing ? i think this is a really good idea

**Comment by rycus86** [comment]
Thanks for the praise! :)
I'd like it to turn into something but haven't been able to spend too much time on it recently. I'm hoping to pick it up when I redo my home stack, but it's really far from being super stable at the moment I think.

If someone would want to use this seriously it would need work and some help would be great with that is what I'm trying to say. :)
