### ISSUE TITLE
connect to docker API via tcp.

### ISSUE THREAD

**Issue by mxrlkn** [rycus86/podlike#4]
You mention in the readme that you can use tcp to connect to the docker API instead of mounting the socket.

I can't find any examples on how to do that. Is it possible or WIP?

Also, very interesting project.

**Comment by rycus86** [comment]
Hey! Thanks! :)
I had to look it up but based on this here: https://github.com/rycus86/podlike/blob/master/pkg/engine/engine.go#L23 it looks like the standard Docker client environment variables should work.
I think it should be `DOCKER_HOST=tcp://host:port` based on the "Environment variables" section in https://docs.docker.com/engine/reference/commandline/cli/

Hope this helps!

**Comment by mxrlkn** [comment]
I actually used DOCKER_HOST on another project. I Didn't realise it was for the docker cli directly. It should work then. Thanks!
