### ISSUE TITLE
Private Registries

### ISSUE THREAD

**Issue by reverendj1** [rycus86/podlike#6]
When a pod image is in a private registry, the existing login credentials don't seem to get used. I get the below error:

```
Attaching to myservice
myservice    | Using API version: 1.40
myservice    | Starting component: mycontainer
myservice    | Pulling image: mydockerregistry/group/project/mycontainer:latest
myservice    | Exited: volume Error: Failed to start volume: Error response from daemon: Get https://mydockerregistry/v2/group/project/mycontainer/manifests/latest: denied: access forbidden
```

If I manually pull it first, it works fine. Am I missing something?

**Comment by rycus86** [comment]
No, unfortunately, that bit is not implemented yet.
Docker registry credentials are not available through the Docker API, and it would need to be given to the controller in this case to use it when pulling images.

I'll try to have a look if this is something easy to do with the golang Docker client.

**Comment by rycus86** [comment]
I found this, which doesn't seem to be too difficult (for basic auth) https://github.com/leopoldxx/godocker/blob/master/docker.go

This would need passing in registry credentials (potentially as Swarm secrets) to the podlike container.
Is that something that would help you here?

**Comment by reverendj1** [comment]
It would be ideal if it somehow passed on the credentials of the user, like the `docker stack deploy --with-registry-auth` argument. If that's not possible, then being able to use Swarm secrets and/or labels would be second best.

**Comment by reverendj1** [comment]
Were you able to come up with anything for this? I have a project this would be great for.

**Comment by rycus86** [comment]
Hi! Haven't had time to look into this yet, sadly.
I could try reviewing a PR if you have time though?
